version: '3.1'

services:

  app:
    container_name: app
    image: index.docker.io/drewcarlson/anystream:latest
    restart: unless-stopped
    command: >
      ./install/server-shadow/bin/server
      -P:app.ffmpegPath=/usr/bin
      -P:app.webClientPath=/app/client-web
      -P:app.databaseUrl=sqlite:/app/config/anystream.db
      -P:app.qbittorrentUrl=http://qbittorrent:9090
      -port=8888
    ports:
      - 8888:8888
    volumes:
      - ./qbittorrent/content:/content
      - ./qbittorrent/downloads:/downloads
      - ./anystream-client-web/build/distributions:/app/client-web
      - ./anystream-server/build/install:/app/install
    links:
      - qbittorrent
    depends_on:
      - qbittorrent

  qbittorrent:
    image: drewcarlson/docker-qbittorrentvpn
    container_name: qbittorrent
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    privileged: true
    environment:
      - VPN_ENABLED=yes
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=8.8.8.8,8.8.4.4
      - WEBUI_PORT=9090
      - INCOMING_PORT=8148
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022
    ports:
      - 9090:9090
    volumes:
      - ./qbittorrent/config:/config
      - ./qbittorrent/downloads:/downloads
      - ./qbittorrent/content:/content
